# Generated by Django 4.0.1 on 2022-04-08 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countryListModel',
            fields=[
                ('countryId', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfoModel',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('mobileNumber', models.IntegerField()),
                ('workNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('GA1', models.CharField(blank=True, max_length=100)),
                ('GA2', models.CharField(blank=True, max_length=100)),
                ('GA3', models.CharField(blank=True, max_length=100)),
                ('GA4', models.CharField(blank=True, max_length=100)),
                ('GB1', models.BooleanField(default=False)),
                ('GB2', models.BooleanField(default=False)),
                ('GB3', models.BooleanField(default=False)),
                ('GB4', models.BooleanField(default=False)),
                ('GD1', models.DateField(blank=True)),
                ('GD2', models.DateField(blank=True)),
                ('GD3', models.DateField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.countrylistmodel')),
            ],
        ),
    ]
