# Generated by Django 4.0.1 on 2022-04-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_alter_customerinfomodel_ga1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfomodel',
            name='GA1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfomodel',
            name='GA2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfomodel',
            name='GA3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfomodel',
            name='GA4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfomodel',
            name='GD1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfomodel',
            name='GD2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfomodel',
            name='GD3',
            field=models.DateField(blank=True, null=True),
        ),
    ]
