# Generated by Django 4.0.1 on 2022-04-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_alter_customerinfomodel_ga1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrylistmodel',
            name='countryName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
