# Generated by Django 4.0.1 on 2022-04-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_alter_countrylistmodel_countryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfomodel',
            name='customerName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customerinfomodel',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customerinfomodel',
            name='mobileNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
