# Generated by Django 4.0.1 on 2022-04-08 22:06

import datetime
from django.db import migrations, models
import numpy


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_alter_customerinfomodel_customername_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfoModel',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=100, unique=True)),
                ('projectDesc', models.CharField(max_length=300)),
                ('startDate', models.DateField(default=datetime.datetime(2022, 4, 9, 2, 6, 56, 78937))),
                ('endDate', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(verbose_name=numpy.require)),
                ('active', models.BooleanField(default=True)),
                ('GA1', models.CharField(blank=True, max_length=100, null=True)),
                ('GA2', models.CharField(blank=True, max_length=100, null=True)),
                ('GB1', models.BooleanField()),
                ('GB2', models.BooleanField()),
                ('GD1', models.DateField(blank=True, null=True)),
                ('GD2', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
