# Generated by Django 4.0.1 on 2022-04-08 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_projectinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfomodel',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projectinfomodel',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 9, 2, 9, 36, 98312)),
        ),
    ]
