# Generated by Django 4.0.1 on 2022-04-09 05:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_alter_projectinfomodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfomodel',
            name='startDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='projectContractModel',
            fields=[
                ('contractId', models.AutoField(primary_key=True, serialize=False)),
                ('contractPeriod', models.CharField(choices=[('3', '3 Month'), ('6', '6 Month'), ('9', '9 Month'), ('12', '12 Month')], max_length=5)),
                ('startDate', models.DateField(default=datetime.datetime.now)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('GA1', models.CharField(blank=True, max_length=100, null=True)),
                ('GB1', models.BooleanField()),
                ('GD1', models.DateField(blank=True, null=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.customerinfomodel')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.projectinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='paymentsModel',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('paymentRef', models.CharField(max_length=100)),
                ('transactionDate', models.DateField(default=datetime.datetime.now)),
                ('paymentType', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], max_length=10)),
                ('paymentAmount', models.IntegerField()),
                ('Currency', models.CharField(choices=[('AED', 'AED'), {'$', 'dollar'}], max_length=6)),
                ('GA1', models.CharField(blank=True, max_length=100, null=True)),
                ('GB1', models.BooleanField()),
                ('GD1', models.DateField(blank=True, null=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.customerinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='commentsModel',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('commentDate', models.DateField(default=datetime.datetime.now)),
                ('comment', models.CharField(max_length=150)),
                ('GA1', models.CharField(blank=True, max_length=100, null=True)),
                ('GB1', models.BooleanField()),
                ('GD1', models.DateField(blank=True, null=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.customerinfomodel')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.projectinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='assignProjectModel',
            fields=[
                ('assignId', models.AutoField(primary_key=True, serialize=False)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.customerinfomodel')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.projectinfomodel')),
            ],
        ),
    ]
