# Generated by Django 4.0.1 on 2022-04-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_assignprojectmodel_assigndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontractmodel',
            name='contractPeriod',
            field=models.CharField(choices=[('3 Month', '3 Month'), ('6 Month', '6 Month'), ('9 Month', '9 Month'), ('12 Month', '12 Month')], max_length=10),
        ),
    ]
