# Generated by Django 4.0.1 on 2022-04-09 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_alter_projectcontractmodel_contractperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsmodel',
            name='projectId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.projectinfomodel'),
            preserve_default=False,
        ),
    ]
