# Generated by Django 4.0.1 on 2022-04-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0012_assignprojectmodel_userlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfomodel',
            name='GB1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfomodel',
            name='GB2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfomodel',
            name='GB3',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfomodel',
            name='GB4',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
