# Generated by Django 4.0.1 on 2022-04-28 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0017_alter_customerinfomodel_gb1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfomodel',
            name='userLogin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
