# Generated by Django 4.0.1 on 2022-04-29 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0018_customerinfomodel_userlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfomodel',
            name='userLogin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
