# Generated by Django 4.0.1 on 2022-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0020_alter_customerinfomodel_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfomodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
