# Generated by Django 4.0.1 on 2022-05-01 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0025_customerinfomodel_createdby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='CreatedBy',
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
