# Generated by Django 4.0.1 on 2022-05-02 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0028_remove_commentsmodel_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='commentDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
