# Generated by Django 4.0.1 on 2022-05-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0029_alter_commentsmodel_commentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='comment',
            field=models.CharField(max_length=400),
        ),
    ]
