# Generated by Django 4.0.1 on 2022-05-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0030_alter_commentsmodel_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignprojectmodel',
            name='projectId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.projectinfomodel'),
        ),
    ]
