# Generated by Django 4.0.1 on 2022-05-03 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0031_alter_assignprojectmodel_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfomodel',
            name='userLogin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='b', to=settings.AUTH_USER_MODEL),
        ),
    ]
