# Generated by Django 4.0.1 on 2022-05-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0032_alter_customerinfomodel_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='testModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userLogin', models.TextField(max_length=10)),
                ('customerId_t', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.customerinfomodel')),
            ],
        ),
    ]
