# Generated by Django 4.0.1 on 2022-05-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0033_testmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='userLogin',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='userLogin_t',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
