# Generated by Django 4.0.1 on 2022-05-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0034_remove_testmodel_userlogin_testmodel_userlogin_t'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='customerId_t',
            new_name='customerIdt',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='userLogin_t',
            new_name='userLogint',
        ),
    ]
