# Generated by Django 4.0.1 on 2022-05-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0035_rename_customerid_t_testmodel_customeridt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignprojectmodel',
            name='userLogin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
