# Generated by Django 4.0.1 on 2022-05-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0036_alter_assignprojectmodel_userlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsmodel',
            name='projectId',
        ),
    ]
