# Generated by Django 4.0.1 on 2022-05-04 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0037_remove_paymentsmodel_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsmodel',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
