# Generated by Django 4.0.1 on 2022-05-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0038_paymentsmodel_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsmodel',
            name='GB1',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
